### ISSUE TITLE
Thumbs should be 1:1 aspect ratio

### ISSUE THREAD

**Issue by rhukster** [absalomedia/grav-theme-future#1]
Thumbnails are epxected to be 1:1 aspect ratio. The ones you currently have are looking a little wonky on the getgrav.org site:

![2015-12-03 at 9 47 am](https://cloud.githubusercontent.com/assets/1084697/11567193/17586e62-99a3-11e5-8352-43cb5071edcd.png)

**Comment by absalomedia** [comment]
Fixed in https://github.com/absalomedia/grav-theme-future/releases/tag/1.0.3
