### ISSUE TITLE
Non valid html

### ISSUE THREAD

**Issue by BugHunter2k** [absalomedia/grav-theme-future#4]
I'm working on a front end editing plugin at the moment. While testing my plugin with diffrent themes i found the future don't play well with me. 
I look at the code and found that the page content is wrapped in <p> Tags, resulting in broken/invalid html when having subheadings or other block elements in content.

**Comment by absalomedia** [comment]
Can you supply an example? It's a bit hard to diagnose without it.

I installed a copy of your Front End plugin & can't replicate the issue. Due to the way the theme is designed, I also can't see the Fred editing icon, which may be an issue with Fred as it assumes the page editing should be on the left.

**Comment by BugHunter2k** [comment]
I got my plugin working. The icon was hidden under the menubar :) After moving it around a little bit I found it. (I didn't figured out why z-index wasn't working here as expected)

Nevertheless you generate invalid HTML for page content with headlines for example: 

```
<p itemprop="articleBody"><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec ultricies tristique nulla et mattis. Phasellus id massa eget nisl mi sagittis et facilisis tortor volutpat. Etiam tincidunt urna mattis erat placerat placerat ac eu tellus.</p>
<h2>Lorem ipsum dolor sit amet,</h2>
<p>consectetur adipiscing elit. Donec ultricies tristique nulla et mattis. Phasellus id massa eget nisl congue blandit sit amet id ligula. Praesent et nulla eu augue tempus sagittis. ac, dictum a nunc.</p></p>
```

You see there is an `<h2>` inside the `<p>` And nestetd `<p>` tags. 

If you don't care about valid code you can close this issue.
Thanks

**Comment by absalomedia** [comment]
@BugHunter2k I've restructured the way the ArticeBody area works. This should remove the issue with the nested `<p>` tags. I'm still unable to reproduce the issue where an extra unclassed `<h2>` element is generated. Release 1.0.6 should help you now
